name: Build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    strategy:
      fail-fast: false
      matrix:
        include: # hier müssen die Pfade angegeben werden
          - app-path: authority-mapper
          - app-path: require-http-header-authenticator
          - app-path: require-role-authenticator
          - app-path: username-from-login-hint-authenticator

    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@9767179088fd2e344d1a24c17404ab809a60f1b6 # v1.0.20
      - if: ${{ hashFiles(format('./{0}/package.json', matrix.app-path))!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@9767179088fd2e344d1a24c17404ab809a60f1b6 # v1.0.20
        with:
          app-path: ${{ matrix.app-path }}
      - if: ${{ hashFiles(format('./{0}/pom.xml', matrix.app-path))!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@9767179088fd2e344d1a24c17404ab809a60f1b6 # v1.0.20
        with:
          app-path: ${{ matrix.app-path }}
